export const FILTER_DATA_UPDATE = 'FILTER_DATA_UPDATE';
export const BIGMOVIE_UPDATE = 'BIGMOVIE_UPDATE';
export const TO_WATCH_UPDATE = 'TO_WATCH_UPDATE';
export const WATCHED_UPDATE = 'WATCHED_UPDATE';
export const GENRE_DATA_UPDATE = 'GENRE_DATA_UPDATE';